### ISSUE TITLE
Do not print environment variables on console

### ISSUE THREAD

**Issue by ehmicky** [bencao/netlify-plugin-inline-functions-env#1]
Environment variables are likely to contain confidential information.
Many build logs are public, therefore printing `process.env` constitutes a security concern even when being a `verbose` flag.

On the other hand, printing the names of each environment variable should be ok, although less useful for debugging.

**Comment by bencao** [comment]
addressed by https://github.com/bencao/netlify-plugin-inline-functions-env/commit/438513b9b9506e7324974153ea98282e853b95dc
