### ISSUE TITLE
Add support for .env.defaults

### ISSUE THREAD

**Issue by tysonmatanich** [bencao/netlify-plugin-inline-functions-env#11]
I have found having a .env.defaults file pretty useful: https://github.com/mrsteele/dotenv-defaults

**Comment by bencao** [comment]
hi Tyson, if I understand correctly, as long as the .env.defaults file is available,`env.defaults` will inject their value properly in runtime right?
The primary purpose for this plugin is to inline those "Build time" environment variables that are ONLY available at build time.
Please let me know if I misunderstood your request.

**Comment by tysonmatanich** [comment]
Their plugin does everything that `dotenv` does but also provides an easy way to set defaults in a separate file.

The approach is similar to having `prod.env` and `dev.env` files, however with that approach both files need to be complete and contain all variables. By having defaults set and source controlled (as long as they aren't secrets) when you start the repo everything works and you can easily see what environment variables are set by default. This makes overriding specific variables per environment easier.

**Comment by bencao** [comment]
I get what you mean to support env.defaults now. 
So current inline functions env does not play well with .env.defaults because the following code:

```
function test() {
  console.log(process.env.VAR_IN_ENV_DEFAULTS);
}
```

with inline-functions-env it would be compile to

```
function test() {
  console.log(undefined);
}
```

I'll propose a solution to address your issue.

**Comment by tysonmatanich** [comment]
I setup a sample test repro to show my use case. It works fine for `netlify dev` but things get messed up on `netlify build`
https://github.com/tysonmatanich/netlify-dotenv-defaults-test

**Comment by bencao** [comment]
Thanks! With PR #14 we can possibly solve the issue with the following change to netlify.toml:

```
[build]
functions = "functions/"

[dev]
port = 8000

[[plugins]]
package = "netlify-plugin-inline-functions-env"
+  [plugins.inputs]
+    exclude = ["SAMPLE_1", "SAMPLE_2", "SAMPLE_3"]
```

the drawback is we need to remember to add to both env.defaults and netlify.toml when we include new environment variables.

**Comment by tysonmatanich** [comment]
I created my own plugin to work around my issue and populate `process.env` with my variables. I have it run on `onPreBuild` and have yours then run on `onBuild`. For some reason when they were both running on `onPreBuild` Netlify wasn't respecting the order in my `netlify.toml`.

Plugin:
```js
const dotenv = require("dotenv-defaults");
module.exports = (inputs) => {
  return {
    onPreBuild: () => {
      dotenv.config({
        path: inputs.env,
        defaults: inputs.defaults,
      });
    },
  };
};

```

**Comment by bencao** [comment]
the above solution is great. I think it worth being published to the public repo and used by others.
