### ISSUE TITLE
Fix Node 10 support

### ISSUE THREAD

**Issue by ehmicky** [bencao/netlify-plugin-inline-functions-env#16]
`Array.flat()` is not supported in Node 10:

https://github.com/bencao/netlify-plugin-inline-functions-env/blob/d4b042817b5566abd9d73819353f320265461bb6/index.js#L39-L40

This could be fixed by using instead: 

```js
const include = inputs.include && [].concat(...[inputs.include])
const exclude = inputs.exclude && [].concat(...[inputs.exclude])
```

**Comment by bencao** [comment]
fixed with v1.0.8
