### ISSUE TITLE
Use `utils.status.show()`

### ISSUE THREAD

**Issue by ehmicky** [bencao/netlify-plugin-inline-functions-env#3]
Do you think some of the `console.log()` might be nice to show in the deploy summary? This would probably need to be shown regardless of whether the `verbose` input is `true`.

To show this information, `utils.status.show()` can be used (documentation [here](https://docs.netlify.com/configure-builds/build-plugins/create-plugins/#logging)).

**Comment by bencao** [comment]
addressed by https://github.com/bencao/netlify-plugin-inline-functions-env/commit/438513b9b9506e7324974153ea98282e853b95dc
