### ISSUE TITLE
Add error handling

### ISSUE THREAD

**Issue by ehmicky** [bencao/netlify-plugin-inline-functions-env#4]
`babel.transformFileAsync()` might fail, for example when the user's Function file has invalid JavaScript. Should that potential error be handled with a `try`/`catch` and report it using `utils.build.failBuild()` (documentation [here](https://docs.netlify.com/configure-builds/build-plugins/create-plugins/#error-reporting))?

**Comment by bencao** [comment]
addressed by https://github.com/bencao/netlify-plugin-inline-functions-env/commit/438513b9b9506e7324974153ea98282e853b95dc

**Comment by ehmicky** [comment]
Great, thanks!
One potential improvement would be to pass the error instance as an option:

```js
return utils.build.failBuild(`Failed to inline function files due to the following error:\n${err.message}`, { error: err });
```

This ensures the original error's stack trace is kept in the build logs.
