### ISSUE TITLE
Not working with ts files &`esbuild` 💔

### ISSUE THREAD

**Issue by zoexx** [bencao/netlify-plugin-inline-functions-env#40]
I switched to `esbuild` as netlify recommended.
then troubles begin : )
```
[[plugins]]
  package = "netlify-plugin-inline-functions-env"
    [plugins.inputs]
    buildEvent = "onBuild"
```

`onPostBuild` got the same out put

I noticed the `netlifyFunctions = await utils.functions.listAll()` just returns all function ts files in src (before bundling).

I printed out the `netlifyFunctions` 

```
────────────────────────────────────────────────────────────────
  3. onBuild command from netlify-plugin-inline-functions-env
────────────────────────────────────────────────────────────────
netlifyFunctions [
  {
    srcFile: '/Users/zoe/sites/xxx/functions/delivery-available-providers/index.ts',
    name: 'delivery-available-providers',
    mainFile: '/Users/zoe/sites/xxx/functions/delivery-available-providers/index.ts',
    runtime: 'js',
    extension: '.ts'
  },
```
since it is `extension: '.ts'` it will not be deal.

if I use a `js` file with `esbuild`, the **source** file will be deal. (should be **dist** files)
```
  {
    srcFile: '/Users/zoe/sites/xxx/functions/test-envs/index.js',
    name: 'test-envs',
    mainFile: '/Users/zoe/sites/xxx/functions/test-envs/index.js',
    runtime: 'js',
    extension: '.js'
  }

inlining /Users/zoe/sites/xxx/functions/test-envs/index.js

(netlify-plugin-inline-functions-env onBuild completed in 1.2s)
```

so, seems like, if there's a way to get the `js` files after bundling then deal the files with `netlify-plugin-inline-functions-env` will work.

Does anyone have ideas ? 😭

cute animal
```
  //
 ('>
 / rr
*\))_
```

**Comment by bencao** [comment]
Can you set buildEvent = "onPostBuild" in netlify.toml to see whether it will work?

**Comment by zoexx** [comment]
> Can you set buildEvent = "onPostBuild" in netlify.toml to see whether it will work?

thanks for your reply! yeah, I've try `onPostBuild` as well, it's same out put (still `extension: '.ts'`) and it deal the `.js` file in source folder (should be dist folder)

**Comment by ziogas** [comment]
Experiencing the same problem in the typescript project (as typescript cloud functions always use `esbuild`). 

Interestingly, rolling back `@netlify/plugin-nextjs` to `3.8.0` solves the issue with this plugin. So it must be that something changed on 3.9.0: https://github.com/netlify/netlify-plugin-nextjs/compare/v3.8.0...v3.9.0

**Comment by Elyx0** [comment]
@zoexx Any luck there?
